apiVersion: v1
kind: Service
metadata:
  name: discov-svc
  labels:
    app: spring
spec:
  type: NodePort
  selector:
    app: demo-kube-eureka
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 31000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discov-deploy
  labels:
    app: spring
spec:
  selector:
    matchLabels:
      app: demo-kube-eureka
  template:
    metadata:
      labels:
        app: demo-kube-eureka
    spec:
      containers:
        - name: discovery
          image: chocogem/demo-kube-eureka:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
      restartPolicy: Always