apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  labels:
    app: spring
spec:
  type: NodePort
  selector:
    app: demo-kube-gateway
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    app: spring
spec:
  selector:
    matchLabels:
      app: demo-kube-gateway
  template:
    metadata:
      labels:
        app: demo-kube-gateway
    spec:
      containers:
        - name: gateway
          image: chocogem/demo-kube-gateway:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 9093
      restartPolicy: Always