server:
  port: 9090

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/chocogem/application-config

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      #http://{service-name}.{name-space}.svc:9091/eureka
      defaultZone: http://discov-svc.default.svc:9091/eureka



