
server:
  port: 9093
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: claim
          uri: lb://claim-service
          predicates:
            - Path=/claims/**
        - id: policy
          uri: lb://policy-service
          predicates:
            - Path=/policies/**
        - id: customer
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
#          filters:
#            PrefixPath=/customers


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka

management.endpoints.web.exposure.include: '*'