apiVersion: v1
kind: Service
metadata:
  name: claim-svc
  labels:
    app: spring
spec:
  type: NodePort
  selector:
    app: demo-kube-claim
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: claim-deploy
  labels:
    app: spring
spec:
  selector:
    matchLabels:
      app: demo-kube-claim
  template:
    metadata:
      labels:
        app: demo-kube-claim
    spec:
      containers:
        - name: claim-service
          image: chocogem/demo-kube-claim:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always