apiVersion: v1
kind: Service
metadata:
  name: config-svc
  labels:
    app: spring
spec:
  selector:
    app: demo-kube-config
  ports:
    - port: 9090
      targetPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deploy
  labels:
    app: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-kube-config
  template:
    metadata:
      labels:
        app: demo-kube-config
    spec:
      containers:
        - name: configuration-service
          image: chocogem/demo-kube-config:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
      restartPolicy: Always