apiVersion: v1
kind: Service
metadata:
  name: policy-svc
  labels:
    app: spring
spec:
  type: NodePort
  selector:
    app: demo-kube-policy
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-deploy
  labels:
    app: spring
spec:
  selector:
    matchLabels:
      app: demo-kube-policy
  template:
    metadata:
      labels:
        app: demo-kube-policy
    spec:
      containers:
        - name: policy-service
          image: chocogem/demo-kube-policy:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
      restartPolicy: Always