apiVersion: v1
kind: Service
metadata:
  name: customer-svc
  labels:
    app: spring
spec:
  type: NodePort
  selector:
    app: demo-kube-customer
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deploy
  labels:
    app: spring
spec:
  selector:
    matchLabels:
      app: demo-kube-customer
  template:
    metadata:
      labels:
        app: demo-kube-customer
    spec:
      containers:
        - name: customer-service
          image: chocogem/demo-kube-customer:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
      restartPolicy: Always